[package]
name = "cli_snake_game"
version = "1.0.0"
authors = ["Beau McCartney <mccartney.beausl@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "*"
rand = "*"
